version: "3.9"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
       - backend-network
  chat:
    build: .
    deploy:
      replicas: 5
    restart: always
    depends_on:
      - redis
    networks:
       - backend-network
  nginx:
    image: nginx
    ports: 
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    command: 'bash -c "nginx -g ''daemon off;''"'
    depends_on: 
        - chat
    networks:
       - backend-network
networks:
    backend-network:
        driver: bridge